### ISSUE TITLE
Ghost weed plants causing chaos

### ISSUE THREAD

**Issue by Dano0942** [echoroleplay/feedback#332]
**Description:** Weed plants (phoenix and yankton) are duplicating/triplicating with the top plant being the only actual plant.

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Plant out a neat crop in the THC basement
2. Come back 24 hours later to harvest an notice multiple plants stacked on each other
3. Try to interact with the plants - only the top plant can be interacted with.
4. Perform gymnastics through the garden trying to ensure all plants are harvested because we are broke AF

**Expected Behavior:** Ghost plants dont exist and actual plants are on the ground where we left them.

**Actual Behavior:** ghost plants exist with the actual plant in the top of the stack

**Screenshot(s)/Video(s):** 

Error when interacting with a ghost plant:
https://i.imgur.com/U7BuGZB.jpeg

The chaos mid-way through the harvest:
https://i.imgur.com/HzKwJu1.jpeg

**Comment by FlawwsX** [comment]
An attempted fix has been pushed. Please let me know if you see improvement next restart.

**Comment by Dano0942** [comment]
Unfortunately it's not fixed.

https://i.imgur.com/9iKtfzv.jpeg
