### ISSUE TITLE
Constant rogue local planes in grapeseed (and in the city)

### ISSUE THREAD

**Issue by BillBloot** [echoroleplay/feedback#410]
**Description:** As of 2 days ago, planes keep spawning in the skies of grapeseed.  Additionally, there are planes and blimps crashing in the city.  

**Reproduction Steps:** Clearly describe the steps to reproduce the bug. 
1. Standing outside Blackwoods.  
2. Repeated planes spawning and attempting to land in grapeseed
3. Some just disappear, some crash into the field, and some crash into the highway

**Expected Behavior:**   While this is not exactly a bug, these local planes were removed some time ago

**Actual Behavior:** Planes to not spawn in

**Screenshot(s)/Video(s):** If possible, add screenshots or videos to help explain your problem.
https://i.imgur.com/78izYcD.jpeg
https://medal.tv/games/gta-v/clips/1jWLNu_FLc6I30/d1337hJeODEB?invite=cr-MSxXSmMsMTM2MDEyNDU0LA

**Comment by FlawwsX** [comment]
We're looking into this and should have it resolved soon.

**Comment by FlawwsX** [comment]
This should be resolved now.

**Comment by BillBloot** [comment]
@FlawwsX Has this been pushed?  Just checked now and the plane respawns are still occurring

https://i.imgur.com/eE53yrl.jpeg
https://i.imgur.com/ceLTbuw.png

**Comment by Bountyrogger** [comment]
Yeah I just saw a crop duster dive bomb the farms in Grapeseed LMAO
